In [2]:
import numpy as np
A=np.array([[1,2,3],[3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [3]:
array =np.zeros((2,3))
print(array)


[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
import numpy as np
import math
array =np.ones((1,5)) #1 Serisi
print("1 Series= ",array)
a2=np.random.randn(3,5) #Random
print("Random Array= ",a2)

sin90=math.sin(math.radians(90)) #sin90 
print("sin 90=",sin90)

1 Series=  [[1. 1. 1. 1. 1.]]
Random Array=  [[-0.75805565 -1.37282469  0.88005914 -1.06664676  1.86644023]
 [-1.56429952 -0.04544795 -2.11905505 -0.78590842  0.14129721]
 [-0.77748991  0.30241518  0.57774699  0.17900536 -1.34940452]]
sin 90= 1.0


In [17]:
#While Func ODD finder
a = 1
while a < 10:
    if a % 2 == 0:
        a += 1
        continue
    print("Odd:", a)
    a += 1

Odd: 1
Odd: 3
Odd: 5
Odd: 7
Odd: 9


In [6]:
#if-else example

print("Select version (1-3)")

version=input()

if version=="1":
    print("Version 1.0 activated")
elif version=="2":
    print("Version 2.0 activated")
elif version=="3":
    print("Version 3.0 activated")
else:
    print("You select wrong version")

Select version (1-3)
5
You select wrong version


In [10]:
def passOrFail(x):
    if x < 50:
        print('You failed')
    elif x>100:
        print("you entered wrong note")
    else:
        print("You passed")
        
passOrFail(35)

You failed
